version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:latest
    environment:
      - ZEEBE_LOG_LEVEL=info
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ./lib/zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./simple-monitor/application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:latest
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    # volumes:
    #   - ./simple-monitor-application.yaml:/usr/local/zeebe/config/application.yaml
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
  rest_api:
    image: node:14.15.0
    container_name: rest_api
    ports:
      - "3000:3000"
    depends_on:
      - zeebe
    volumes:
      - ./restExample:/fastify
    command: bash -c "npm i -g fastify-cli && cd /fastify && npm i && npm run dev"
    networks:
      - zeebe_network
  worker:
    image: node:14.15.0
    container_name: worker
    depends_on:
      - zeebe
    volumes:
      - ./oddOrEvenWorker:/worker
    command: bash -c "cd /worker && npm i && node index.js"
    networks:
      - zeebe_network
